Use map instead of array in checking merged_files
tani/vim-jetpack pull request #46
Opened 2022-03-23 12:06 UTC by hrsh7th

This PR aims to improve the merging performance.

I think the `if filter(copy(destfiles), 'index(merged_files, v:val) >= 0') != []` is very slow.

2022-03-23 14:44 UTC, tani requested changes
Thank you for improving the performance.
Please consider making it faster. Best,

2022-03-23 14:44 UTC, tani commented on autoload/jetpack.vim
> +      let files = filter(copy(files), '!s:ignorable(v:val)')
We can avoid copy the variable by `call filter(files, '!s:ignorable(v:val)')`

2022-03-23 14:44 UTC, tani commented on autoload/jetpack.vim
> +      call map(copy(files), 'extend(merged_files, { v:val: v:true })')
We can avoid copy the variable by `call map(files, extend(merged_files, { v:val: v:true }))`

2022-03-24 12:23 UTC, tani commented on autoload/jetpack.vim
> +      if file_index < len(files) - 1
例えば10個のファイルが存在して，1つだけファイル名が重複した場合を考えてみます．
ファイル名のリストの末尾にこのファイルが存在すると，286行目でbreakが発生するときの
file_indexの値は9になります．そして289行目での判定では `len(files) - 1`は 9であるため，
その結果は偽となります．つまり重複したファイルが存在しているのに，このパッケージは`unbundle` に格納されません．したがって，CIがエラーで落ちてしまっていますね．

2022-03-25 04:50 UTC, merged

2022-03-25 04:51 UTC, tani commented
Thank you so much for your contribution!

2022-03-25 05:09 UTC, hrsh7th commented
Thank you for review and merge!