feat: pkg.config
tani/vim-jetpack pull request #78
Opened 2022-10-05 14:43 UTC by uga-rosa

2022-10-05 15:06 UTC, tani commented
ありがとうございます。この場合、optが設定されていないとき 510行目付近で continue実行されてしまい、configの有無に関係なく 読み込まれてい、またconfigに対する autocmdが実行されないと思われます。

まずテストの追加をお願いします。その後, テストを通過するためにどうすればよいか議論しましょう。
よろしくお願いします。

2022-10-05 15:11 UTC, uga-rosa commented
588行目で追加してますが、vim script側で処理したほうがいいんですかね？packerとの互換機能なのでこっちで処理していいかなと思ったのですが
テスト了解です

2022-10-05 15:32 UTC, tani commented
opt=trueしてましたね。見落としてました。OKだと思います。

2022-10-06 13:03 UTC, uga-rosa commented
うーん、この書き方だとインストールされる前に次の処理に行っちゃうみたいですね。
`s:setup()`と同様の書き方のはずなんですが

2022-10-06 13:18 UTC, uga-rosa commented
通ったけどVimEnter発行されてるんですかねこれ

2022-10-07 06:39 UTC, tani commented
ありがとうございます． `v:vim_did_enter` によって発行の有無が確認できますね．
そこの確認もお願いできますでしょうか？ありがとうございます．

2022-10-07 15:30 UTC, uga-rosa commented
suiteの中で登録したautocmdが発行されたかどうかってどこに書けばいいんでしよう…？

2022-10-14 10:33 UTC, uga-rosa commented
requireが失敗しているということは、インストールできてないってことですよね。どうしてだろう

2022-10-15 08:59 UTC, uga-rosa commented
そもそもpacker styleのテストがなかったので足しましたが、これが通ってませんね。

2022-10-26 11:08 UTC, tani commented
ありがとうございます。 `package_root` の値が packer.nvim の非互換なので、どうしましょうか ...

2022-10-26 11:12 UTC, uga-rosa commented
[packer.init](https://github.com/wbthomason/packer.nvim#custom-initialization)で設定するのですが、jetpack.initって名前使うのはどうかなあと思いまして。
記法はお任せしますが

2022-10-26 11:53 UTC, uga-rosa commented
setup（ソース前に読み込む設定）も追加したいんですが、PR分けた方がいいでしょうか？

2022-10-29 07:25 UTC, uga-rosa commented
そろそろ考え方固まったでしょうか。。。？

2022-10-29 07:57 UTC, tani commented
すみません。体調ダウンしてておくれました! 対応します。

2022-10-29 08:00 UTC, tani commented
まず、setupについては、すでに paq.nvim対応のために追加しているので、名前空間を分けましょう。
別のプルリクエストでお願いします。以下のような形でどうでしょうか?

```lua
require('jetpack.packer').setup { ... }
require('jetpack.packer').startup { ... }
require('jetpack.paq').setup { ... }
```

2022-10-29 08:02 UTC, tani commented
package_root については、やはり公式と揃えたいので、 fnamemodifyでディレクトリを適宜調整する処理を挟んでいただけますか?

2022-10-29 08:18 UTC, uga-rosa commented
あー、packerのsetupはconfigと同様のuseで使うフィールド名です。読み込むタイミングが違うやつ。なので名前空間は問題ないですかね。PRは分けます。
packer.initの場所は今ので良いですか？変えた方が？

2022-10-29 08:25 UTC, tani commented
なるほど。名前空間を汚染しないこと承知しました。ご説明ありがとうございます。
PR分けていただけると便利なのでお願いします。

今後さらに互換性を高めるためには上記のように分けたほうが、
より安心して機能追加できるので分けていただけますか?

2022-10-29 10:12 UTC, uga-rosa commented
windowsだけ落ちてるんですがなんででしょうこれ

2022-10-29 11:20 UTC, uga-rosa commented
準備できたのでレビューお願いします。

2022-10-29 11:49 UTC, tani commented on doc/jetpack.txt
> +    require('jetpack.paq') {
更新されてたんですね。古い記法から新しくしてくださりありがとうございます。

2022-10-29 11:51 UTC, tani commented on plugin/jetpack.vim
> +        execute printf('autocmd Jetpack VimEnter * ++once ++nested silent! packadd %s', pkg_name)
自分用メモ: configが設定されているとき かつ hook が設定されてないとき、VimEnterで packaddされる。

2022-10-29 11:53 UTC, tani commented on plugin/jetpack.vim
> +      execute printf('autocmd User Jetpack%sPost %s', event, pkg.config)
SourcePost イベント は VimLでしか発火しないので、luaだとconfigが実行されない恐れがありますが、
解決したんでしたっけ?

2022-10-29 11:54 UTC, tani commented on plugin/jetpack.vim
> +end
クールな書き方ですね。すばらしい。

2022-10-29 11:59 UTC, tani reviewed
おおむね良いのですが、懸念事項を確認させてください。

SourcePostイベントは Luaモジュールに対して発火しないと記憶していたのですが、
configはlua系のんvimプラグインでも動作していますか?

2022-10-29 12:00 UTC, uga-rosa commented
すっかり忘れてました。
nvim-web-deviconsでもplugin/*.vimあるから発火してるのか

2022-10-29 12:01 UTC, tani commented
あ、大丈夫そう? > https://neovim.io/doc/user/autocmd.html
uga-rosaさんの需要が満せるか、lua系でもテストしてみていただけますか?

2022-10-29 12:02 UTC, uga-rosa commented
lua/以下はplugin/以下と違って自動読み込みされないのでそっちが問題ですね。autoloadに近い
よさげなプラグイン調べて試してみます。

2022-10-29 12:03 UTC, tani commented
度重なる仕様要求すみません。よろしくお願いします。
協力ありがとうございます。心強いです。

2022-10-29 12:18 UTC, uga-rosa commented
ちゃんと(?)落ちました。
イベント設定されてるものは対処できるでしょうが、手動packaddには対応できない気が、、、いいアイデアありますかね

2022-10-29 12:54 UTC, tani commented
グローバルにrequire上書きすることで、requireした時に発火するようにハックしたことがあります。流石に邪悪なので、取り下げた案でしたが、もはや致し方なしですかね。packerはどうしているのでしょうか？

2022-10-29 12:55 UTC, uga-rosa commented
packer.load読んでみましたが、こういうのをかませれば対応できそうです。
```vim
function! jetpack#load(pkg_name) abort
  if !has_key(s:packages, a:pkg_name)
    return
  endif
  let pkg = s:packages[a:pkg_name]
  execute 'silent! packadd' a:pkg_name
  if pkg.config !=# ''
    execute pkg.config
  endif
endfunction
```

2022-10-29 13:00 UTC, tani commented
ご教示くださりありがとうございます。
テスト追加も検討してくださると嬉しいです。
よろしくお願いします。

2022-10-29 13:20 UTC, uga-rosa commented
これでどうでしょう

2022-10-29 13:33 UTC, uga-rosa commented
コミット混ぜちゃったので再push
ちゃんと通ってますね。これで大丈夫そうかな

2022-10-30 13:53 UTC, uga-rosa commented
懸念も解消されたと思うのですがどうでしょう

2022-10-30 14:26 UTC, tani requested changes
loadのアイディアは素晴しいと思います。感謝します。
loadをドキュメントに追加していただき、
これもLuaから使えるようにしていただいて、無事マージしたいと思います。

2022-10-30 14:26 UTC, tani commented on plugin/jetpack.vim
> +endfunction
Luaの関数としてもtrue/falseを返すように以下の変更はどうでしょう
```suggestion
function! jetpack#load(pkg_name) abort
  if !has_key(s:packages, a:pkg_name)
    return v:false
  endif
  let pkg = s:packages[a:pkg_name]
  execute 'silent! packadd' a:pkg_name
  if pkg.config !=# ''
    execute pkg.config
  endif
  return v:true
endfunction
```

2022-10-30 14:26 UTC, tani commented on plugin/jetpack.vim
>  for _, name in pairs({'begin', 'end', 'add', 'names', 'get', 'tap', 'sync'}) do
```suggestion
for _, name in pairs({'begin', 'end', 'add', 'names', 'get', 'tap', 'sync', 'load'}) do
```

2022-10-30 15:06 UTC, tani commented
あともう一点多分、問題ないと思うのですが、configが設定されていてもプラグインは高速化のためのマージ処理に巻き込まれて　pack/jetpack/opt/_ ディレクトリに押し込まれます。詳しくはmerge関数をご覧ください。したがってpackadd pkg_name は実は多くの場合失敗してるはずです。なぜならpack/jetpack/opt/pkg_name なるディレクトリは存在しないからです。

それでもテストが通るのはpackadd _が一番最初に実行されるからです。これが実行されることでconfig関数は問題なく実行できているのだと思います。

これで問題ないかLuaユーザーの視点から確認いただけますか？

2022-10-30 15:15 UTC, uga-rosa commented
このテストからjetpack#load消したらrequireで見つからないって落ちますよ？なので問題ないのかと思ってました。
このあと入れるpacker.nvimのsetup optionがちゃんと機能するかが気がかりですね。プラグインが読み込まれる前に設定しないといけない変数なんかを設定する用途に使いたいので。

2022-10-30 15:21 UTC, tani commented
コメントありがとうございます。ちょっと気になったので。setupで引っかかるかもしれないのですね。
そのときは、僕のほうでもアシストできることがあると思うので、気軽にpingしてください。
先の件を除き、完璧なPRだと思います。このたびは貢献ありがとうございました。
初期のVim-jetpackのとき以来の(機能単位として)巨大な機能追加となりました。
自分では作れなかったと思います。実装能力を尊敬致します。

マージします!!! 🍻

2022-10-30 15:21 UTC, merged