Ask a user before deleting jetpack
tani/vim-jetpack pull request #98
Opened 2022-12-09 10:34 UTC by ryicoh

https://user-images.githubusercontent.com/37844673/206682849-87d9a270-890c-4f3f-9441-dab9bce2896e.mov

2022-12-09 10:39 UTC, ryicoh commented on plugin/jetpack.vim
> +endfunction
This is a copy of vim-plug. It's licence is MIT.
https://github.com/junegunn/vim-plug/blob/master/plug.vim#L316

2022-12-09 12:04 UTC, tani commented
ありがとうございます。とても、かっこ良い動作だと思います。
いくつか気になる点がるのでコメントします。


- [ ] `Jetpack 'tani/vim-jetpack', { opt: v:true }` の記述があるときは、削除しても問題ないはずなので聞かなくても良いはずですね。
- [ ] こういうプロンプトが表示されているっていうことをテストにすることってできるのでしょうか。もし現状で難しそうなら、"削除しそうになる -> 例外を投げる -> 例外をキャッチして尋ねる -> y なら再度実行 -> n なら終了" のように実装すれば、例外を投げたということはThemisでチェェックできた思うので、検討してみてください。
- [ ] コードを借用した場合は、借用したコードのリンクとライセンスファイルをコメントで記載をお願いします
      MIT License であれば、ライセンスファイルのリンクと使用した範囲の明示のみで十分だったと思います。

2022-12-09 14:08 UTC, ryicoh commented
コメントありがとうございます！

> Jetpack 'tani/vim-jetpack', { opt: v:true } の記述があるときは、削除しても問題ないはずなので聞かなくても良いはずですね。

こちら了解です！

>  こういうプロンプトが表示されているっていうことをテストにすることってできるのでしょうか。もし現状で難しそうなら、"削除しそうになる -> 例外を投げる -> 例外をキャッチして尋ねる -> y なら再度実行 -> n なら終了" のように実装すれば、例外を投げたということはThemisでチェェックできた思うので、検討してみてください。

Vimにもテストがあったのですね〜！知らなかったです。ちょっと見てみます。

> コードを借用した場合は、借用したコードのリンクとライセンスファイルをコメントで記載をお願いします

MIT License であれば、ライセンスファイルのリンクと使用した範囲の明示のみで十分だったと思います。

こちら了解です！


今回、雑に実装してみたのですが、tani さんからみて、方向性あってそうですか？
というのも、シンプルで早いのがコンセプトだと思うので、あんまりカッコ良さ求めてなかったりとか、
この警告出す機能のためだけに１０行ほど増えてしまってて、それを今後もメンテナンスするのはtaniさんだと思うので、
少しでも違うかなという部分あれば、おっしゃっていただけると嬉しいです🙇

実装してみて特に、今後もこのメッセージがユーザに表示されてしまうのが重くなっちゃいそうなのかなとかちょっと感じてます。

>  call s:ask("Add a \"Jetpack 'tani/vim-jetpack', {'opt': 1}\" line to your vimrc (Enter)")

2022-12-12 15:48 UTC, tani requested changes
全体的に素晴しい出来だと思います。ありがとうございます。
とくに、input()のテストなどを根気強く取り組んでくださり感謝します。
少し条件漏れがあったので、テストを充実しつつ、条件漏れを潰し次第マージさせてください。

2022-12-12 15:48 UTC, tani commented on plugin/jetpack.vim
> +      if pkg_name == 'vim-jetpack' && !s:ask('Delete "' . pkg_name . '"?')
`Jetpack 'tani/vim-jetpack', { 'opt': 1 }` が既にvimrc に書かれていて、
少し古い vim-jetpack が、インストールされている状態を考えます。

- 338行目: vimrc に記述があるため `!has(...)` は `v:false` になります。
- 339行目: すこし古い vim-jetpack がある場合 `.output` は `Already up to date.` でな無いため、`s:delcalaredpackages ... !~# 'Already up to date.'` は `v:true` になります。
- 340行目: インストール済のため `pkg_name` には `vim-jetpack` が格納されているケースがあります
- 340行目: 上記の条件により `s:ask()` が実行されます。

以上の分析から、以前私がお願いした「vim-jetpack が記述されているときは 聞かなくても良い」という指摘を修正し切れていないと思われます。

2022-12-12 15:48 UTC, tani commented on plugin/jetpack.vim
> +        call s:ask("Add a \"Jetpack 'tani/vim-jetpack', {'opt': 1}\" line to your vimrc. Are you okay?")
この文だと、"Are you okay?" は,このプログラムが、その設定を勝手に書き込む許可をとろうとしているように読めてしまします。以下はどうでしょうか? 「次のコード片を追加してください: "Jetpack 'tani/vim-jetpack', { 'opt': v:true }"」

```suggestion
        call s:ask("Please add the following snippet: \"Jetpack 'tani/vim-jetpack', {'opt': 1}\"")
```

2022-12-17 15:21 UTC, ryicoh commented on plugin/jetpack.vim
> +      if pkg_name == 'vim-jetpack' && !s:ask('Delete "' . pkg_name . '"?')
https://github.com/tani/vim-jetpack/pull/98/commits/5c290570f0e48f9cd42dda1516acd6bb778feaa9

こちら修正致しました。また、古いvim-jetpackの場合のテストも追加いたしました。

2022-12-17 15:56 UTC, tani commented
CIのエラーのうち、パーミッションに起因するエラーはこちらのミスで、開発ブランチにて修正済みです。
git cherry-pick を実行すれば直ると思います。 当該 commit は https://github.com/tani/vim-jetpack/commit/9a8d7fc9b327de6fbcddc405bc5f7bbb4d5dc72b#diff-e1b493543a2b746436011f9c6bccd73dbe4b051d706fa6da348bccf6e7104e0cL76 になります。
Ubuntu版の古いVimでCIが失敗してますね。あと Windows 版の Vimでも落ちるのに macOSのVimだと成功するというのは、なにが起きているのでしょうか ... うーん。ひとまず、デバッグしやすい環境のCIを通すことを目標に調整してみていただけますか?

2022-12-18 07:07 UTC, ryicoh commented
tani さん、いつもご丁寧にありがとうございます！
すごい細かくテスト書かれててあっぱれです。

ローカルでDockerでUbuntu環境試してみましたがテスト落ちないっすねぇ〜、もうちょっと細かく見てみます！
Windowsも環境ありますので見ます！

一旦cherrypickしてみます、こちらのPRはrebaseして開発ブランチに向けた方が良かったりしましたら、おっしゃってください！

2022-12-20 10:12 UTC, ryicoh reviewed
お手隙でレビューお願いいたします🙇

2022-12-20 10:12 UTC, ryicoh commented on .github/workflows/test.yml
> +
Vim 用と Neovim用に分けました。

`version: ${{ vi == "vim" ? 'v8.1.2424' : 'stable' }}` みたいにできれば便利だったのですが、、、

> Run Neovim tests with ${{ matrix.dl }} and ${{ matrix.cp }}

この英語間違えてますかね、、以下の方がいいでしょうか？

> Run tests with ${{ matrix.dl }} and ${{ matrix.cp }} for Neovim

2022-12-20 12:49 UTC, tani commented on .github/workflows/test.yml
> +
matrix.include / matrix.exclude を使うとマトめられます。
あらたに version という変数を追加して、`vi: neovim` もしくは `os: windows-2022` もしくは `os: macos-11` のときに `version: v8.1.2110` のケースを除くというはどうでしょうか

```yaml
version: [stable, v8.1.2110]
exclude:
  - vi: neovim
    version: v8.1.2110
  - os: macos-11
    version: v8.1.2110
  - os: windows-2022
    version: v8.1.2110
```

2022-12-20 12:49 UTC, tani commented on plugin/jetpack.vim
> +    let is_jetpack = pkg_name == 'vim-jetpack' || pkg_name == 'vim-jetpack.git'
正規表現を使うのはどうでしょうか

2022-12-20 12:53 UTC, ryicoh commented on plugin/jetpack.vim
> +    let is_jetpack = pkg_name == 'vim-jetpack' || pkg_name == 'vim-jetpack.git'
そうしますか〜、好みではないですが。。

2022-12-20 12:53 UTC, ryicoh commented on .github/workflows/test.yml
> +
これはクールですね！

2022-12-20 15:52 UTC, ryicoh commented on plugin/jetpack.vim
> +    let is_jetpack = pkg_name == 'vim-jetpack' || pkg_name == 'vim-jetpack.git'
ブツブツ言ってましたけど、綺麗になりました😄

https://github.com/tani/vim-jetpack/pull/98/commits/e2bc6ae9f4d579e05df83af540b3eae260460838

2022-12-20 15:58 UTC, ryicoh commented on .github/workflows/test.yml
> +
そういえば、Windowsだと v8.1.2110 がないらしく、v8.1.2424 を使ったのですがどうしましょうか？？
と思ったらここから取ってるはずなのでありそうではありますけど、なぜだ。。
https://github.com/vim/vim-win32-installer/tree/v8.1.2110

2022-12-20 22:16 UTC, ryicoh commented on .github/workflows/test.yml
> +
https://github.com/ryicoh/vim-jetpack/actions/runs/3742068754/jobs/6352618888

やはり無さそうです！

2022-12-21 04:25 UTC, tani approved these changes
この度は、根気強く取り組んでくださりありがとうございました。
シンプルかつエレガントな変更になったと思います。安心して取り込むことができます。
ありがとうございました。

2022-12-21 04:26 UTC, merged

2022-12-21 08:28 UTC, ryicoh commented
こちらこそありがとうございます🙇
時間かかってしまいましたが、最後まで付き合って頂きありがとうございました！